default_aoai_config:
  endpoint: <Full deployment URL>
  model: <gpt-4 or gpt-3.5-turbo>
  compute_target: <Compute target with model access>
  max_errors: 10
  workers: 10

# If being used as an embedding config, then the endpoint will look like:
# https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/embeddings?api-version=2023-05-15