defaults:
  - _self_
  - aml_config
  - aoai_config

zeroshot_config:
  pipeline:
    base_experiment_name: biosbias_json
    tags:
    default_compute_target: isolatedcompute
  biosbias_dataset: biosbias_small:1
  json_guidance_program: simple_biosbias_json.py
  aoai_config: ${ default_aoai_config }
